In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from urllib.parse import urlparse

In [3]:
df1 = pd.read_csv("../data/raw/urlset.csv")

In [4]:
df1.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0

# add https:// or http://
 jhape nhi h taki parse wali lib ache se kaam kr ske

In [5]:
def normalize(url):
    if not url.startswith (("http://", "https://")):
        url = "http://" + url
    return url

In [6]:
df1['domain_normal'] = df1['domain'].apply(normalize)

In [7]:
url = df1["domain_normal"].iloc[0]
print(url)

http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526

In [8]:
parsed = urlparse(url)

In [9]:
parsed.path

'/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php'

In [10]:
parsed.scheme

'http'

In [11]:
parsed.netloc

'nobell.it'

In [12]:
parsed.query

'cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

In [13]:
print("URL:", url)
print("Scheme:", parsed.scheme)
print("Hostname:", parsed.netloc)
print("Path:", parsed.path)
print("Query:", parsed.query)

URL: http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526
Scheme: http
Hostname: nobell.it
Path: /70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php
Query: cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526

In [14]:
print(len(url))
print(len(parsed.netloc))
print(len(parsed.path))
print(len(parsed.query))

232
9
125
90

In [15]:
df1.shape

(95913, 15)

In [16]:
df1 = df1.dropna(subset=["label"])

In [17]:
df1.shape

(95913, 15)

In [18]:
df1['label'].value_counts()

label
0.0    48009
1.0    47904
Name: count, dtype: int64

In [19]:
df = df1

In [20]:
df.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label,domain_normal
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0,http://nobell.it/70ffb52d079109dca5664cce6f317...
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0,http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0,http://serviciosbys.com/paypal.cgi.bin.get-int...
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0,http://mail.printakid.com/www.online.americane...
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0,http://thewhiskeydregs.com/wp-content/themes/w...

In [21]:
print(df[['domain_normal','domain']].head())

                                       domain_normal  \
0  http://nobell.it/70ffb52d079109dca5664cce6f317...
1  http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2  http://serviciosbys.com/paypal.cgi.bin.get-int...
3  http://mail.printakid.com/www.online.americane...
4  http://thewhiskeydregs.com/wp-content/themes/w...

                                              domain
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....
3  mail.printakid.com/www.online.americanexpress....
4  thewhiskeydregs.com/wp-content/themes/widescre...

In [22]:
print("Hostname:", parsed.hostname)
print("Port:", parsed.port)
print("Username:", parsed.username)
print("Password:", parsed.password)

Hostname: nobell.it
Port: None
Username: None
Password: None

In [23]:
path_parts = parsed.path.split('/')
print(path_parts)

['', '70ffb52d079109dca5664cce6f317373782', 'login.SkyPe.com', 'en', 'cgi-bin', 'verification', 'login', '70ffb52d079109dca5664cce6f317373', 'index.php']

In [24]:
path_parts = [x for x in parsed.path.split("/") if x]

print(path_parts)

['70ffb52d079109dca5664cce6f317373782', 'login.SkyPe.com', 'en', 'cgi-bin', 'verification', 'login', '70ffb52d079109dca5664cce6f317373', 'index.php']

In [25]:
print("Number of path parts:", len(path_parts))

Number of path parts: 8

In [26]:
from urllib.parse import parse_qs
query_params = parse_qs(parsed.query)

In [27]:
print(query_params)

{'cmd': ['_profile-ach'], 'outdated_page_tmpl': ['p/gen/failed-to-load'], 'nav': ['0.5.1'], 'login_access': ['1322408526']}

In [28]:
print("Number of query parameters:", len(query_params))

Number of query parameters: 4

In [29]:
url = df['domain_normal'].iloc[0]

In [30]:
url

'http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

### Features in next block
- `url_length`, `num_digits`, `num_letters`, `num_dots`, `num_hyphens`, `num_underscores`, `num_at`, `num_percent`, `num_question`, `num_ampersand`, `num_equal`

In [31]:
url_length = len(url)
num_digits = sum(c.isdigit() for c in url)
num_letters = sum(c.isalpha() for c in url)
num_dots = url.count(".")
num_hyphens = url.count("-")
num_underscores = url.count("_")
num_at = url.count("@")
num_percent = url.count("%")
num_question = url.count("?")
num_ampersand = url.count("&")
num_equal = url.count("=")

In [32]:
print(url_length)
print(num_digits)
print(num_letters)
print(num_dots)
print(num_hyphens)
print(num_underscores)
print(num_at)
print(num_percent)
print(num_question)
print(num_ampersand)
print(num_equal)

232
58
139
6
4
4
0
0
1
3
4

### Feature in next block
- `digit_ratio`

In [33]:
digit_ratio = num_digits / url_length if url_length else 0

### Feature in next block
- `letter_ratio`

In [34]:
letter_ratio = num_letters / url_length if url_length else 0

# special chars ratio

### Features in next block
- `special_chars`, `special_chars_ratio`

In [35]:
special_chars = sum(not c.isalnum() for c in url)
special_chars_ratio = special_chars/url_length if url_length else 0

# path_depth

### Feature in next block
- `path_depth`

In [36]:
path_parts = [x for x in parsed.path.split('/') if x]
path_depth = len(path_parts)

# subdomain

In [37]:
hostname_parts = parsed.hostname.split(".")
print(hostname_parts)

['nobell', 'it']

In [38]:
print("Hostname parts:", len(hostname_parts))

Hostname parts: 2

Lekin yahan ek important complication hai: .co.uk, .com.au jaise multi-part public suffixes hote hain. Isliye abhi simple dot-count ko exact “subdomain count” mat bolna.

### Feature in next block
- `num_subdomain_like_parts`

In [39]:
num_subdomain_like_parts = max(len(hostname_parts) - 2, 0)

### Feature in next few blocks
- `suspicious_word_count`

In [40]:
suspicious_words = [
    "login",
    "verify",
    "verification",
    "account",
    "secure",
    "update",
    "confirm",
    "signin",
    "password",
    "credential"
]

In [41]:
url_lower = url.lower()

In [42]:
suspicious_word_count = sum(
    word in url_lower for word in suspicious_words
)

In [43]:
print(suspicious_word_count)

2

### Feature in next block
- `is_ip`

In [44]:
import ipaddress
hostname = parsed.hostname
try:
    ipaddress.ip_address(hostname)
    is_ip = 1
except ValueError:
    is_ip = 0
print("Hostname:", hostname)
print("Is IP address:", is_ip)

Hostname: nobell.it
Is IP address: 0

### Features in next block
- `encoded_character_count`

In [45]:
import re
encoded_parts = re.findall(r'%[0-9a-fA-F]{2}', url)
encoded_character_count = len(encoded_parts)
print("Encoded parts:", encoded_parts)
print("Encoded character count:", encoded_character_count)

Encoded parts: []
Encoded character count: 0

### Feature in next block
- `encoded_ratio`

In [46]:
encoded_ratio = len(encoded_parts) / url_length if url_length else 0
print("Encoded character ratio:", encoded_ratio)

Encoded character ratio: 0.0

In [47]:
hostname_parts = hostname.split(".")
print("Hostname parts:", hostname_parts)
print("Number of dots in hostname:", hostname.count("."))

Hostname parts: ['nobell', 'it']
Number of dots in hostname: 1

### Features in next block
- `hostname_length`, `hostname_digits`, `hostname_digit_ratio`

In [48]:
hostname = parsed.hostname if parsed.hostname else ""
hostname_length = len(hostname)
hostname_digits = sum(c.isdigit() for c in hostname)
hostname_digit_ratio = (
    hostname_digits / hostname_length
    if hostname_length else 0
)
print("Hostname:", hostname)
print("Hostname length:", hostname_length)
print("Hostname digits:", hostname_digits)
print("Hostname digit ratio:", hostname_digit_ratio)

Hostname: nobell.it
Hostname length: 9
Hostname digits: 0
Hostname digit ratio: 0.0

### Feature in next block
- `hostname_hyphens`

In [49]:
hostname_hyphens = hostname.count("-")
print("Hostname hyphens:", hostname_hyphens)

Hostname hyphens: 0

### Feature in next block
- `longest_hostname_parts`

In [50]:
hostname_parts = hostname.split('.')
longest_hostname_parts = max(
    [len(part) for part in hostname_parts],
    default=0
)

In [51]:
longest_hostname_parts

6

### Features in next block
- `path_length`, `path_digits`, `path_special_chars`

In [52]:
path = parsed.path
path_length = len(path)
path_digits = sum(c.isdigit() for c in path)
path_special_chars = sum(
    not c.isalnum() and c != "/"
    for c in path
)
print("Path length:", path_length)
print("Path digits:", path_digits)
print("Path special characters:", path_special_chars)

Path length: 125
Path digits: 45
Path special characters: 4

# high entropy ka matlab phishing nahi hai.

# counter string se character count krta h
url = "google.com"

Counter({
    'o': 2,
    'g': 1,
    'l': 1,
    'e': 1,
    '.': 1,
    'c': 1,
    'm': 1
})

### Feature in next block
- `entropy`

In [53]:
from collections import Counter
import math

counter = Counter(url)

entropy = 0

for count in counter.values():
    probability = count / len(url)
    entropy -= probability * math.log2(probability)

print("URL entropy:", entropy)

URL entropy: 5.046608107554676

### Feature in next block
- `path_entropy`

In [54]:
path_counter = Counter(path)
path_entropy = 0
if path:
    for count in path_counter.values():
        probability = count / len(path)
        path_entropy -= probability * math.log2(probability)
print("Path entropy:", path_entropy)

Path entropy: 4.760639584764059

### Features in next block
- `query_length`, `query_digits`, `query_special_chars`

In [55]:
query = parsed.query
query_length = len(query)
query_digits = sum(c.isdigit() for c in query)
query_special_chars = sum(
    not c.isalnum()
    for c in query
)
print("Query length:", query_length)
print("Query digits:", query_digits)
print("Query special characters:", query_special_chars)

Query length: 90
Query digits: 13
Query special characters: 18

### Feature in next block
- `unique_query_parameters`

In [56]:
query_params = parse_qs(query)
unique_query_parameters = len(query_params)
print("Unique query parameters:", unique_query_parameters)

Unique query parameters: 4

### Feature in next block
- `has_at_symbol`

In [57]:
has_at_symbol = 1 if "@" in url else 0

print("Has @:", has_at_symbol)

Has @: 0

### Feature in next block
- `has_encoding`

In [58]:
has_encoding = 1 if encoded_character_count > 0 else 0

### Feature in next block
- `double_slash_in_path`

In [59]:
double_slash_in_path = 1 if "//" in parsed.path else 0
print("Double slash in path:", double_slash_in_path)

Double slash in path: 0

# fregment
#https://example.com/login#verify

#verify ko fragment kehte hain.

### Features in next block
- `fragment`, fragment length

In [60]:
fragment = parsed.fragment

print("Fragment:", fragment)
print("Fragment length:", len(fragment))

Fragment:
Fragment length: 0

### Feature in next block
- `has_fragment`

In [61]:
has_fragment = 1 if fragment else 0
print("Has fragment:", has_fragment)

Has fragment: 0

In [62]:
import re
import math
import ipaddress
from collections import Counter
from urllib.parse import urlparse, parse_qs
suspicious_words = [
    "login",
    "verify",
    "verification",
    "account",
    "secure",
    "update",
    "confirm",
    "signin",
    "password",
    "credential"
]

In [63]:
def extract_features(url):
    parsed = urlparse(url)
    hostname = parsed.hostname if parsed.hostname else ""
    path = parsed.path
    query = parsed.query
    
    # Basic URL features
    
    url_length = len(url)
    hostname_length = len(hostname)
    path_length = len(path)
    query_length = len(query)
    
    path_parts = [x for x in path.split('/') if x]
    path_depth = len(path_parts)
    
    query_params = parse_qs(query)
    unique_query_parameters = len(query_params)
    
    # Character features
    
    num_digits = sum(c.isdigit() for c in url)
    num_letters = sum(c.isalpha() for c in url)
    num_dots = url.count(".")
    num_hyphens = url.count("-")
    num_underscores = url.count("_")
    num_at = url.count("@")
    num_percent = url.count("%")
    num_question = url.count("?")
    num_ampersand = url.count("&")
    num_equal = url.count("=")
    
    digit_ratio = (
        num_digits / url_length
        if url_length else 0
    )

    letter_ratio = (
        num_letters / url_length
        if url_length else 0
    )

    special_chars = sum(
        not c.isalnum()
        for c in url
    )

    special_chars_ratio = (
        special_chars / url_length
        if url_length else 0
    )
    
      # IP address
      
    try:
        ipaddress.ip_address(hostname)
        is_ip = 1
    except ValueError:
        is_ip = 0
        
    # Hostname features
    
    hostname_parts = hostname.split('.') if hostname else []
    
    hostname_digit_count = sum(c.isdigit() for c in hostname)
    
    hostname_digit_ratio = (
        hostname_digit_count / hostname_length
        if hostname_length else 0
    )
    
    hostname_hyphens = hostname.count("-")

    hostname_part_count = len(hostname_parts)
    
    num_subdomain_like_parts = max(
        hostname_part_count - 2,
        0
    )

    longest_hostname_part = max(
        [len(part) for part in hostname_parts],
        default=0
    )
    
    # Path features
    
    path_digits = sum(
        c.isdigit() for c in path
    )

    path_special_chars = sum(
        not c.isalnum() and c != "/"
        for c in path
    )
    
    # Query features
    
    query_digits = sum(
        c.isdigit() for c in query
    )

    query_special_chars = sum(
        not c.isalnum()
        for c in query
    )
    
    
    # Suspicious words
    
    url_lower = url.lower()
    suspicious_word_count = sum(
        word in url_lower
        for word in suspicious_words
    )

    has_suspicious_word = (
        1 if suspicious_word_count > 0 else 0
    )
    
    # URL entropy
    
    entropy = 0
    if url_length > 0:
        counter = Counter(url)
        for count in counter.values():
            probability = count / url_length
            entropy -= (
                probability *
                math.log2(probability)
            )
    
     # Path entropy
     
    path_entropy = 0
    if path_length > 0:
        path_counter = Counter(path)
        for count in path_counter.values():
            probability = count / path_length
            path_entropy -= (
                probability *
                math.log2(probability)
            )
            
                # URL encoding
                
    encoded_parts = re.findall(
        r'%[0-9a-fA-F]{2}',
        url
    )

    encoded_character_count = len(encoded_parts)
    
    encoded_ratio = (
        encoded_character_count / url_length
        if url_length else 0
    )

    has_encoding = (
        1 if encoded_character_count > 0 else 0
    )
    
    # Other structural features
    
    has_at_symbol = 1 if "@" in url else 0

    double_slash_in_path = (
        1 if "//" in path else 0
    )

    fragment = parsed.fragment
    fragment_length = len(fragment)
    has_fragment = (
        1 if fragment else 0
    )
    
    # Return all features
    
    return {
        "url_length": url_length,
        "hostname_length": hostname_length,
        "path_length": path_length,
        "query_length": query_length,
        "path_depth": path_depth,
        "unique_query_parameters": unique_query_parameters,
        "num_digits": num_digits,
        "num_letters": num_letters,
        "num_dots": num_dots,
        "num_hyphens": num_hyphens,
        "num_underscores": num_underscores,
        "num_at": num_at,
        "num_percent": num_percent,
        "num_question": num_question,
        "num_ampersand": num_ampersand,
        "num_equal": num_equal,
        "digit_ratio": digit_ratio,
        "letter_ratio": letter_ratio,
        "special_chars_ratio": special_chars_ratio,
        "is_ip": is_ip,
        "hostname_digit_count": hostname_digit_count,
        "hostname_digit_ratio": hostname_digit_ratio,
        "hostname_hyphens": hostname_hyphens,
        "hostname_part_count": hostname_part_count,
        "num_subdomain_like_parts": num_subdomain_like_parts,
        "longest_hostname_part": longest_hostname_part,
        "path_digits": path_digits,
        "path_special_chars": path_special_chars,
        "query_digits": query_digits,
        "query_special_chars": query_special_chars,
        "suspicious_word_count": suspicious_word_count,
        "has_suspicious_word": has_suspicious_word,
        "url_entropy": entropy,
        "path_entropy": path_entropy,
        "encoded_character_count": encoded_character_count,
        "encoded_ratio": encoded_ratio,
        "has_encoding": has_encoding,
        "has_at_symbol": has_at_symbol,
        "double_slash_in_path": double_slash_in_path,
        "fragment_length": fragment_length,
        "has_fragment": has_fragment
    }

In [64]:
url = df["domain_normal"].iloc[0]

In [65]:
test_features = extract_features(url)
print(test_features)

{'url_length': 232, 'hostname_length': 9, 'path_length': 125, 'query_length': 90, 'path_depth': 8, 'unique_query_parameters': 4, 'num_digits': 58, 'num_letters': 139, 'num_dots': 6, 'num_hyphens': 4, 'num_underscores': 4, 'num_at': 0, 'num_percent': 0, 'num_question': 1, 'num_ampersand': 3, 'num_equal': 4, 'digit_ratio': 0.25, 'letter_ratio': 0.5991379310344828, 'special_chars_ratio': 0.15086206896551724, 'is_ip': 0, 'hostname_digit_count': 0, 'hostname_digit_ratio': 0.0, 'hostname_hyphens': 0, 'hostname_part_count': 2, 'num_subdomain_like_parts': 0, 'longest_hostname_part': 6, 'path_digits': 45, 'path_special_chars': 4, 'query_digits': 13, 'query_special_chars': 18, 'suspicious_word_count': 2, 'has_suspicious_word': 1, 'url_entropy': 5.046608107554676, 'path_entropy': 4.760639584764059, 'encoded_character_count': 0, 'encoded_ratio': 0.0, 'has_encoding': 0, 'has_at_symbol': 0, 'double_slash_in_path': 0, 'fragment_length': 0, 'has_fragment': 0}

In [66]:
print("Number of features:", len(test_features))

Number of features: 41

In [67]:
features_df = df1["domain_normal"].apply(extract_features).apply(pd.Series)

In [68]:
features_df.shape

(95913, 41)

In [69]:
features_df["label"] = df1["label"].values

In [70]:
features_df.shape

(95913, 42)