In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from urllib.parse import urlparse

In [7]:
df1 = pd.read_csv("../data/raw/urlset.csv")

In [8]:
df1.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0

# add https:// or http://
 jhape nhi h taki parse wali lib ache se kaam kr ske

In [9]:
def normalize(url):
    if not url.startswith (("http://", "https://")):
        url = "http://" + url
    return url

In [10]:
df1['domain_normal'] = df1['domain'].apply(normalize)

In [11]:
url = df1["domain_normal"].iloc[0]
print(url)

http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526

In [12]:
parsed = urlparse(url)

In [13]:
parsed.path

'/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php'

In [14]:
parsed.scheme

'http'

In [15]:
parsed.netloc

'nobell.it'

In [16]:
parsed.query

'cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

In [17]:
print("URL:", url)
print("Scheme:", parsed.scheme)
print("Hostname:", parsed.netloc)
print("Path:", parsed.path)
print("Query:", parsed.query)

URL: http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526
Scheme: http
Hostname: nobell.it
Path: /70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php
Query: cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526

In [18]:
print(len(url))
print(len(parsed.netloc))
print(len(parsed.path))
print(len(parsed.query))

232
9
125
90

In [19]:
df1.shape

(95913, 15)

In [20]:
df1 = df1.dropna(subset=["label"])

In [21]:
df1.shape

(95913, 15)

In [22]:
df1['label'].value_counts()

label
0.0    48009
1.0    47904
Name: count, dtype: int64

In [23]:
df = df1

In [24]:
df.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label,domain_normal
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0,http://nobell.it/70ffb52d079109dca5664cce6f317...
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0,http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0,http://serviciosbys.com/paypal.cgi.bin.get-int...
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0,http://mail.printakid.com/www.online.americane...
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0,http://thewhiskeydregs.com/wp-content/themes/w...

In [25]:
df1.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label,domain_normal
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0,http://nobell.it/70ffb52d079109dca5664cce6f317...
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0,http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0,http://serviciosbys.com/paypal.cgi.bin.get-int...
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0,http://mail.printakid.com/www.online.americane...
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0,http://thewhiskeydregs.com/wp-content/themes/w...

In [26]:
print(df[['domain_normal','domain']].head())

                                       domain_normal  \
0  http://nobell.it/70ffb52d079109dca5664cce6f317...
1  http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2  http://serviciosbys.com/paypal.cgi.bin.get-int...
3  http://mail.printakid.com/www.online.americane...
4  http://thewhiskeydregs.com/wp-content/themes/w...

                                              domain
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....
3  mail.printakid.com/www.online.americanexpress....
4  thewhiskeydregs.com/wp-content/themes/widescre...

In [27]:
print(url)

http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526

In [28]:
print("Hostname:", parsed.hostname)
print("Port:", parsed.port)
print("Username:", parsed.username)
print("Password:", parsed.password)

Hostname: nobell.it
Port: None
Username: None
Password: None

In [29]:
path_parts = parsed.path.split('/')
print(path_parts)

['', '70ffb52d079109dca5664cce6f317373782', 'login.SkyPe.com', 'en', 'cgi-bin', 'verification', 'login', '70ffb52d079109dca5664cce6f317373', 'index.php']

In [30]:
path_parts = [x for x in parsed.path.split("/") if x]

print(path_parts)

['70ffb52d079109dca5664cce6f317373782', 'login.SkyPe.com', 'en', 'cgi-bin', 'verification', 'login', '70ffb52d079109dca5664cce6f317373', 'index.php']

In [31]:
print("Number of path parts:", len(path_parts))

Number of path parts: 8

In [37]:
from urllib.parse import parse_qs
query_params = parse_qs(parsed.query)

In [39]:
print(query_params)

{'cmd': ['_profile-ach'], 'outdated_page_tmpl': ['p/gen/failed-to-load'], 'nav': ['0.5.1'], 'login_access': ['1322408526']}

In [40]:
print("Number of query parameters:", len(query_params))

Number of query parameters: 4

In [41]:
df.head()

,domain,ranking,mld_res,mld.ps_res,card_rem,ratio_Rrem,ratio_Arem,jaccard_RR,jaccard_RA,jaccard_AR,jaccard_AA,jaccard_ARrd,jaccard_ARrem,label,domain_normal
0,nobell.it/70ffb52d079109dca5664cce6f317373782/...,10000000,1.0,0.0,18,107.611111,107.277778,0.0,0.0,0.0,0.0,0.8,0.795729,1.0,http://nobell.it/70ffb52d079109dca5664cce6f317...
1,www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...,10000000,0.0,0.0,11,150.636364,152.272727,0.0,0.0,0.0,0.0,0.0,0.768577,1.0,http://www.dghjdgf.com/paypal.co.uk/cycgi-bin/...
2,serviciosbys.com/paypal.cgi.bin.get-into.herf....,10000000,0.0,0.0,14,73.500000,72.642857,0.0,0.0,0.0,0.0,0.0,0.726582,1.0,http://serviciosbys.com/paypal.cgi.bin.get-int...
3,mail.printakid.com/www.online.americanexpress....,10000000,0.0,0.0,6,562.000000,590.666667,0.0,0.0,0.0,0.0,0.0,0.859640,1.0,http://mail.printakid.com/www.online.americane...
4,thewhiskeydregs.com/wp-content/themes/widescre...,10000000,0.0,0.0,8,29.000000,24.125000,0.0,0.0,0.0,0.0,0.0,0.748971,1.0,http://thewhiskeydregs.com/wp-content/themes/w...

In [42]:
url = df['domain_normal'].iloc[0]

In [43]:
url

'http://nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

In [47]:
print("length of url : " , len(url))
print("number of digits : " , sum(c.isdigit() for c in url))
print("number of letters : " , sum(c.isalpha() for c in url))
print("dots : " , url.count('.'))
print("hyphens : " , url.count('_'))

length of url :  232
number of digits :  58
number of letters :  139
dots :  6
hyphens :  4